### ISSUE TITLE
Move server only views off of tablet app

### ISSUE THREAD

**Issue by mikeymckay** [mikeymckay/coconut#154]
As the datasets grow, this will be a bigger and bigger problem.

**Comment by gmcressman** [comment]
What functionality of lost if this is done?

**Comment by mikeymckay** [comment]
None. It just adds a layer of complexity in having to determine which
queries must be on both the server and tablet. This means we can no longer
say that the exact same application is on both the tablet and server - but
it means that indexing on the tablets is much faster when a couple thousand
record are present.

**Comment by gmcressman** [comment]
Can the app determine whether it is on a mobile device and change synch behavior automatically? (Speaking from complete ignorance.)

**Comment by mikeymckay** [comment]
It's not an issue of sync behavior. The database keeps lists of all queries
that it must index in order to keep the results fast. If any query in a
list changes, the entire list of queries must be re-indexed. Before we just
had one list, so if any query changed, even if it was only every used on
the server, all of the queries had to be re-indexed everywhere. By
separating the queries into a list that only need to be run on the server,
if and when they change, the tablets won't have to re-index those queries,
or indeed every index them.

**Comment by gmcressman** [comment]
That helps me understand. Thanks.

**Comment by alisonperez** [comment]
Hi Sir Gordon, Mike, I have refollowed the coconut engine and would lilke to explore more about it (sans WAH application or use). This discussion is helpful to understand the intricacies of the engine.

**Comment by gmcressman** [comment]
@mikeymckay, I believe that, with Coconut Clinic, you have effectively done load testing of synch with some 30K records. Is that correct?

**Comment by gmcressman** [comment]
@alisonperez, It's good to see your comment in this issue thread.

**Comment by mikeymckay** [comment]
Yes. But.

If most of the records are the same, syncing these records is easy -
couchdb keeps track of changes so it knows what docs may or may not require
syncing.

If you are syncing 30K records to an empty database over a slow connecton,
then it's painful.

If we have a bunch of data already and we are loading a new device, then we
always want to preload it at the beginning to minimize big syncs.

**Comment by mikeymckay** [comment]
Indeed welcome Alison! I'm happy to setup a Skype call if you want to chat
about it more. It's easier to Skype from Nairobi than from DC!

**Comment by mikeymckay** [comment]
This is pretty much done, and certainly done for https://github.com/ICTatRTI/coconut-mobile
