### ISSUE TITLE
Ability to create new issues

### ISSUE THREAD

**Issue by mikeymckay** [mikeymckay/coconut#168]
We should call these “Incidents and Problems”

I have the following structure in mind:

Date incident/problem reported:

Type of incident/problem
DMSO issues
Motorcycles
Phone/Tablet
Network issues
Epidemic alerts
Other
<we will add others>

Description of incident/problem

Action taken/investigation (include date of action)

Solution

Date resolved:

This needs to be implemented immediately.

**Comment by gmcressman** [comment]
Who is responsible for responding to each issue? Issue assignment?

**Comment by mikeymckay** [comment]
Each issue has an "Assigned To" field. In some cases this should be
assigned automatically. In others, someone will need to assign it. I'm
considering something meta as well - an issue in case an issue has existed
for more than X days without being assigned.
