### ISSUE TITLE
Update Epidemic Thresholds

### ISSUE THREAD

**Issue by mikeymckay** [mikeymckay/coconut#176]
Epidemic threshold lists the following alerts:

```
Facility with 10 or more cases
Facility with 5 or more cases in under 5s
Shehia with 10 or more cases
Shehia with 5 or more cases in under 5s
Village (household + neighbors) with 5 or more cases
District - statistical method (todo)
```

We agreed that these made sense with the exception of the District alert, which will be removed, since there isn't a district wide action that would be taken if an alert was raised. In other words, it is better to have actionable alerts that for small geographies.

Unfortunately it was determined that the current method for calculating alerts is ininsufficient. The current method tests the threshold criteria against the cases that are reported during the fixed week period Sunday – Monday. This approach can miss cases that occur around one of the week boundaries. It also means that an alert can only be detected when a week is completed. Hence, we decided that the alert detection must occur on a rolling basis. Each day, the alert criteria should be tested for cases from past 7 days. Furthermore, if an alert is raised for a specific criteria and geography, it will not be re-raised for the next 7 days.

**Comment by gmcressman** [comment]
Make sure to abstract and generalize. Administrative units and threshold levels will be different in other countries.
