### ISSUE TITLE
USSD Notification with no ID

### ISSUE THREAD

**Issue by mikeymckay** [mikeymckay/coconut#20]
Has caused endless loop of SMS.

**Comment by mikeymckay** [comment]
Not sure why MEEDS created a notification with no ID.

**Comment by gmcressman** [comment]
Any way to prevent this causing problems in Coconut? Log the error, but ignore the notification?

**Comment by mikeymckay** [comment]
We need a more robust way of handling errors. The goal is to be able to
turn over all error logging to the team in Zanzibar so that they can
resolve problems. We aren't quite there yet. Also, if MEEDS generates
something without an ID, it's a big problem so I don't want to handle it
too elegantly.
