### ISSUE TITLE
On older tablets - slow

### ISSUE THREAD

**Issue by mikeymckay** [mikeymckay/coconut#42]
Going to a new tab or searching is really slow. Needs optimization.

**Comment by mikeymckay** [comment]
Thanks for reporting @alisonperez (this should add you to the email updates for this bug).

**Comment by alisonperez** [comment]
Mike, the Galaxy Tab P1000, as far as the Greenhills hack is concerned, is only up to Android firmware 2.3.6. Still when using MM in the galaxy tabs, it does not not save as well as it is slow. So we have to separate issues here. How should we approach this from application level?

**Comment by mikeymckay** [comment]
Thanks @alisonperez it does sound like there are multiple issues going there. There are multiple things we can do to test it. One good thing to test would be to use adb to forward port 5984 on the tablet to port 5985 on your laptop. Once you have your laptop connected and USB debugging on, the command is

```
./adb forward tcp:5985 tcp:5984
```

You can then point your browser on your laptop at http://localhost:5985 and it will be accessing the couchdb server on the tablet. We can then test to see if data is being saved.

Also for these devices - I assume these are from fresh installs? Has the application ever worked on any of these devices?

**Comment by mikeymckay** [comment]
Also, I am currently rewriting how that main page works. I am creating a system that will setup cached queries of the data for that page - but it is going to take a bit of work to make it work perfectly.

**Comment by mikeymckay** [comment]
Closing this since it is really old and not in use.
