### ISSUE TITLE
the system takes the user back to complaints 2 though it was previously marked as none.

### ISSUE THREAD

**Issue by mikeymckay** [mikeymckay/coconut#95]

**Comment by mikeymckay** [comment]
Just saw presenting complaint 4, even though 2 was marked as none

**Comment by mikeymckay** [comment]
This seems to be caused by action_on_change code being run on invisible elements.

**Comment by mikeymckay** [comment]
In order to reproduce:

*Create a client visit
- Press none on the 2nd complaint
- This will hide complaints 3-4
- Reload page, skip logic is rerun, but seems to unhide 3-4 because 3 is not marked none (according to debug)

**Comment by fetmar** [comment]
Should be working now.
